#:schema node_modules/wrangler/config-schema.json
name = "todo_remix_project"
compatibility_date = "2024-09-09"
pages_build_output_dir = "./build/client"
send_metrics = false

# ##################### PRODUCTION / LOCAL #####################
vars = { ENVIRONMENT = "production" }
# kv_namespaces = [
#   { binding = "MAIN_KV", id = "TODO:" },
# ]
# d1_databases = [
#   { binding = "MAIN_D1", database_id = "n/a", database_name = "d1_main", migrations_table = "d1_migrations", migrations_dir = "db/drizzle"},
# ]

# ##################### PREVIEW #####################
[env.preview]
vars = { ENVIRONMENT = "preview" }
# kv_namespaces = [
#   { binding = "MAIN_KV", id = "TODO:" },
# ]
# d1_databases = [
#   { binding = "MAIN_D1", database_id = "n/a", database_name = "d1_main", migrations_table = "d1_migrations", migrations_dir = "db/drizzle"},
# ]

[dev]
ip = "0.0.0.0"
port = 8788
